USERNAME = '<SPOTFY_USER_NAME>'
SPOTIPY_CLIENT_ID = '<SPOTIPY_CLIENT_ID>'
SPOTIPY_CLIENT_SECRET = 'SPOTIPY_CLIENT_SECRET'
SPOTIPY_REDIRECT_URI = 'http://<ADDRESS>/spotifyredirect'
PERMISSION_SCOPE = 'user-modify-playback-state user-read-currently-playing user-read-playback-state'
